In [1]:
#Import packages

from time import time
import re
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.model_selection import GridSearchCV
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

#Import custom class and functions

import sys
sys.path.append("../app/customized_class")
from input_data import InputData

In [2]:
def load_data(database_filepath):
    
    '''
    
    This function load a database of cleaned properties and remove non informative variables like this:
    
    -'l2', 'l3', 'l4', 'l5', 'l6', 'Region'
    -'missing_l2', missing_l3', 'missing_l4', 'missing_l5', 'missing_l6'
    
    - 'l2' is removed because is redundant with 'l2shp'
    - 'Region' is removed because a department(l2shp) belongs to a single region, therefore the department defines the region,
       and this can lead to collinearity problems.
    - 'missing_l2' and 'missing_price' are removed because are constant.(no missing values in this columns)
    - lat and lon are in this dataframe but no in the model. They are used for visualizations.
    
    In addition to this we also remove values for properties other than houses or apartments, because the model
    only include this categories.
    
    Params:
        database_filepath (string): Path to sqlLite database
    Returns:
        df(pandas DataFrame): Matrix with features for train model and visualizations (lat and lon columns) and
                              target column ('price')
        
    '''
    engine = create_engine('sqlite:///'+database_filepath)
    df = pd.read_sql_table("Cleaned_prices",con=engine)
    
    columns_to_drop = ['l2', 'l3', 'l4', 'l5', 'l6','Region','missing_l2','missing_l3', 'missing_l4',
                       'missing_l5', 'missing_l6', 'missing_price']
    df = df.drop(columns_to_drop, axis=1)
    df = df[df['property_type'].isin(['Casa','Apartamento'])]
    
    return df

def adjust_data_for_model(df):
    
    '''
    This function the data in convenient format for the stage modelling. Some operations made are:
    
        1. Remove incomplete rows, that is, rows which have more than 2 missing fields in this list: 
           [rooms, log_surface_total, log_surface_covered, bathrooms]
        2. Exclude departments with less of 100 rows in the dataframe
        3. Include dummy variables for categorical variables: property_type, and l2shp (Department)
           using One-Hot Encoding because they are nominal variables. Here the original categorical variables
           are droped, except for l2shp because is ussefull for input median in missing values in a posterior step.
        4. Replace price for log10(price).
        5. Split the dataframe en covariates and target variable (X,y)
        
        
    Parameters:
    -----------
        df(pandas DataFrame): DataFrame with relevant columns and rows for modelling stage
    
    Returns:
    -----------
        
        df(pandas DataFrame): DataFrame with features adjusted for modelling stage
        
    '''
    
    # Step 1: Remove incomplete rows:
    
    columns = ['missing_rooms', 'missing_surface_total', 'missing_surface_covered','missing_bathrooms']
    counts = df[columns].apply(sum,axis=1)
    df = df[counts<=2]

    # Step 2: Exclude departments with less of 100 points.
    
    rows_by_departments = df['l2shp'].value_counts()
    departments_to_exclude = list(rows_by_departments[rows_by_departments<100].index)
    df = df[~df['l2shp'].isin(departments_to_exclude)]
    
    # Step 3: Include dummy variables:
    
    var_cat = df.select_dtypes(include=['object']).copy().columns
    for col in var_cat:
        try:
            
            if col!='l2shp':
                df = pd.concat([df.drop(col,axis=1),pd.get_dummies(df[col], prefix = col, prefix_sep = "_", drop_first = True, 
                                                                   dummy_na = False, dtype=int)],axis=1)
            else:
                df = pd.concat([df,pd.get_dummies(df[col], prefix = col, prefix_sep = "_", drop_first = True, 
                                                                   dummy_na = False,dtype=int)],axis=1)
                
        except Exception as e:
            print(col, "processing error")
            print(e)
        
    # Step 4. Replace price for log10(price):
    
    df['price'] = np.log10(df['price'])
    
    # Step 5. Split the dataframe en covariates and target variable (X,y)
    
    X = df.loc[:,df.columns!="price"]
    y = df['price']
    
    return X,y

In [3]:
df = load_data("../data/PropertiesPrices.db")
display(df)
df, y = adjust_data_for_model(df)
display(df)

,lat,lon,rooms,bedrooms,bathrooms,surface_covered,property_type,surface_total,price,missing_lat,missing_lon,missing_rooms,missing_bedrooms,missing_bathrooms,missing_surface_total,missing_surface_covered,l2shp
5,6.338954,-75.541284,NaN,NaN,NaN,NaN,Apartamento,NaN,162000000.0,0,0,1,1,1,1,1,ANTIOQUIA
14,6.172401,-75.609512,NaN,NaN,1.0,NaN,Apartamento,NaN,150000000.0,0,0,1,1,0,1,1,ANTIOQUIA
15,6.313522,-75.559738,NaN,NaN,2.0,NaN,Apartamento,NaN,320000000.0,0,0,1,1,0,1,1,ANTIOQUIA
16,6.156883,-75.628126,NaN,NaN,2.0,NaN,Apartamento,NaN,375000000.0,0,0,1,1,0,1,1,ANTIOQUIA
17,6.192737,-75.593727,NaN,NaN,2.0,NaN,Apartamento,NaN,280000000.0,0,0,1,1,0,1,1,ANTIOQUIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595378,1.149300,-76.646600,4.0,NaN,2.0,NaN,Casa,243.0,250000000.0,0,0,0,1,0,0,1,PUTUMAYO
595379,1.178700,-76.878500,NaN,NaN,NaN,NaN,Casa,NaN,81000000.0,0,0,1,1,1,1,1,PUTUMAYO
595389,NaN,NaN,2.0,NaN,1.0,78.0,Apartamento,NaN,113000000.0,1,1,0,1,0,1,0,PUTUMAYO
595390,NaN,NaN,2.0,NaN,NaN,86.0,Apartamento,NaN,123000000.0,1,1,0,1,1,1,0,PUTUMAYO
595414,2.567761,-72.639653,NaN,NaN,10.0,NaN,Casa,NaN,750000000.0,0,0,1,1,0,1,1,GUAVIARE

,lat,lon,rooms,bedrooms,bathrooms,surface_covered,surface_total,missing_lat,missing_lon,missing_rooms,...,l2shp_HUILA,l2shp_MAGDALENA,l2shp_META,l2shp_NARIÑO,l2shp_NORTE DE SANTANDER,l2shp_QUINDIO,l2shp_RISARALDA,l2shp_SANTANDER,l2shp_TOLIMA,l2shp_VALLE DEL CAUCA
166,6.205000,-75.549004,NaN,3.0,4.0,NaN,259.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
167,6.216000,-75.608002,NaN,2.0,2.0,NaN,76.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
168,6.228000,-75.565002,NaN,2.0,2.0,NaN,68.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
169,5.617000,-75.623001,NaN,4.0,2.0,NaN,196.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
170,6.342000,-75.557999,NaN,5.0,2.0,NaN,80.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594703,10.474775,-73.248602,3.0,NaN,2.0,56.0,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
594704,10.476000,-73.250000,NaN,2.0,2.0,NaN,63.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
594705,10.475000,-73.250999,NaN,2.0,2.0,NaN,60.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
594706,10.485000,-73.277000,NaN,4.0,4.0,NaN,120.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
594822,NaN,NaN,3.0,NaN,4.0,380.0,1200.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
print(df['l2shp'].value_counts())
print(df.columns)

CUNDINAMARCA          35718
ANTIOQUIA             25778
VALLE DEL CAUCA       16270
ATLANTICO              8702
CALDAS                 4475
BOLIVAR                4231
RISARALDA              3689
SANTANDER              3454
QUINDIO                3123
NORTE DE SANTANDER     2894
MAGDALENA              1315
CORDOBA                1198
TOLIMA                 1118
META                    800
CAUCA                   644
HUILA                   573
NARIÑO                  400
BOYACA                  236
CESAR                   117
Name: l2shp, dtype: int64
Index(['lat', 'lon', 'rooms', 'bedrooms', 'bathrooms', 'surface_covered',
       'surface_total', 'missing_lat', 'missing_lon', 'missing_rooms',
       'missing_bedrooms', 'missing_bathrooms', 'missing_surface_total',
       'missing_surface_covered', 'l2shp', 'property_type_Casa',
       'l2shp_ATLANTICO', 'l2shp_BOLIVAR', 'l2shp_BOYACA', 'l2shp_CALDAS',
       'l2shp_CAUCA', 'l2shp_CESAR', 'l2shp_CORDOBA', 'l2shp_CUNDINAMARCA',
       'l2shp_HUILA', 'l2shp_MAGDALENA', 'l2shp_META', 'l2shp_NARIÑO',
       'l2shp_NORTE DE SANTANDER', 'l2shp_QUINDIO', 'l2shp_RISARALDA',
       'l2shp_SANTANDER', 'l2shp_TOLIMA', 'l2shp_VALLE DEL CAUCA'],
      dtype='object')

In [5]:
transformer = InputData()
df_mod = transformer.fit_transform(df)

In [7]:
df_mod.shape()

TypeError: 'tuple' object is not callable

### Pipeline

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn.svm import LinearSVR

from sklearn.base import BaseEstimator
class DummyEstimator(BaseEstimator):
    def fit(self): pass
    def score(self): pass

In [82]:
def build_model():
    
    '''
    This function construct a pipeline with custom transformer and estimators. The pipeline is passed to grid search function
    for tuning parameter for estimators. The pipeline include FeatureUnion based in custom transformer.
    
    Params:
        None
    Returns:
        cv(GridSearch object): An object of class GridSearch fitting over train data. The object have an attribute "best_estimator_"
                               that contain the best model finded.
    
    '''
    
    pipeline = Pipeline([
             ('input', InputData()),
             ('scaler', StandardScaler()),
             ('clf', DummyEstimator())])
#   
#   
#    pipeline = Pipeline([
#            ('transformer', Pipeline([
#                ('input', InputData()),
#                ('scaler', StandardScaler())
#            ])),
#            ('clf', DummyEstimator())
#    ])
    
    
   # pipeline = Pipeline([
   #     ('features', FeatureUnion([
   #         ('input', InputData()),
   #         ('scaler', StandardScaler())
   #     ])),
   #     ('clf', DummyEstimator())
   # ])

    print(pipeline.get_params())
    
    # Estimator 1: LinearRegression (clasic model):
    
    fit_intercept = [False, True] 
    
    # Estimator 2: Stochastic Gradient Descent:

    # The gradient of the loss is estimated each sample at a time and the model is updated along the way with
    # a decreasing strength schedule (aka learning rate). 
    
    # Choosen loss functions for SGD
    
    loss_function_SGD =["squared_loss", "huber", "epsilon_insensitive", "squared_epsilon_insensitive"]
    
    # Epsilon parameter according loss function selected:
    
    epsilon_huber = [0.4,0.7,1]
    epsilon_epsilon_insensitive = [0.01,0.1,0.2]
    epsilon_squared_epsilon_insensitive = [0.01,0.1,0.2]
    learning_rate = ["invscaling", "adaptive"]
    
    # Estimator 3: Support Vector Regression with Linear Kernel
    
    # Analogously to SVM for classification problem, the model produced by Support Vector Regression depends only
    # on a subset of the training data, because the cost function ignores samples whose prediction is close to their target.
        
    loss_functions_SVR = ["epsilon_insensitive", "squared_epsilon_insensitive"]
    
    # Candidate learning algorithms and their hyperparameters
    
    # Note that the SGDRegressor is splitted in several versions because loss functions is related to specific epsilon
    # values

    search_space = [{'clf': [LinearRegression()],
                    'clf__fit_intercept': fit_intercept},
                    {'clf': [SGDRegressor()],
                     'clf__loss': ['squared_loss']},
                    {'clf': [SGDRegressor()],
                     'clf__loss': ['huber'],
                     'clf__epsilon': epsilon_huber,
                     'clf__learning_rate': learning_rate},
                    {'clf': [SGDRegressor()],
                     'clf__loss': ['epsilon_insensitive'],
                     'clf__epsilon': epsilon_epsilon_insensitive,
                     'clf__learning_rate': learning_rate},
                    {'clf': [SGDRegressor()],
                     'clf__loss': ['squared_epsilon_insensitive'],
                     'clf__epsilon': epsilon_squared_epsilon_insensitive,
                     'clf__learning_rate': learning_rate},
                    {'clf': [LinearSVR()],
                     'clf__loss': loss_functions_SVR}
                   ]

    #Create grid search

    cv = GridSearchCV(pipeline, search_space, n_jobs=-1)
    
    return cv

In [84]:
#df = load_data("../data/PropertiesPrices.db")
#df, y = adjust_data_for_model(df)

X, y = df, y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 10)

# The model will be trained without l2shp, lat and lon variables, these are dropped. 
# They were necessary up to this point for display purposes.

X_train_mod = X_train.drop(['lat','lon'], axis=1) 

display(X_train_mod)

print('Building model...')
model = build_model()

print('Training model...')
start_time = time()
model.fit(X_train_mod, y_train)
end_time = time()
print("The time for training was: {}".format(end_time-start_time))

,rooms,bedrooms,bathrooms,surface_covered,surface_total,missing_lat,missing_lon,missing_rooms,missing_bedrooms,missing_bathrooms,...,l2shp_HUILA,l2shp_MAGDALENA,l2shp_META,l2shp_NARIÑO,l2shp_NORTE DE SANTANDER,l2shp_QUINDIO,l2shp_RISARALDA,l2shp_SANTANDER,l2shp_TOLIMA,l2shp_VALLE DEL CAUCA
235013,2.0,2.0,2.0,77.0,NaN,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
431478,2.0,NaN,2.0,83.0,83.0,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
193043,5.0,5.0,3.0,340.0,250.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
168414,2.0,2.0,2.0,84.0,NaN,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
426624,3.0,NaN,4.0,182.0,NaN,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456027,3.0,NaN,3.0,145.0,671.0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
236300,2.0,2.0,1.0,40.0,NaN,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
461094,3.0,NaN,2.0,100.0,NaN,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
544234,NaN,4.0,3.0,NaN,105.0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
394928,3.0,3.0,3.0,99.0,109.0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Building model...
{'memory': None, 'steps': [('input', InputData(include=['rooms', 'surface_total', 'surface_covered', 'bathrooms'],
          include_log=['surface_total', 'surface_covered'],
          segmentation_col='l2shp')), ('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('clf', DummyEstimator())], 'verbose': False, 'input': InputData(include=['rooms', 'surface_total', 'surface_covered', 'bathrooms'],
          include_log=['surface_total', 'surface_covered'],
          segmentation_col='l2shp'), 'scaler': StandardScaler(copy=True, with_mean=True, with_std=True), 'clf': DummyEstimator(), 'input__include': ['rooms', 'surface_total', 'surface_covered', 'bathrooms'], 'input__include_log': ['surface_total', 'surface_covered'], 'input__segmentation_col': 'l2shp', 'scaler__copy': True, 'scaler__with_mean': True, 'scaler__with_std': True}
Training model...
The time for training was: 424.3010630607605

In [85]:
best_model = model.best_estimator_
print(best_model)
model_filepath = "regressor.pkl"
pickle.dump(model, open(model_filepath, 'wb'))

Pipeline(memory=None,
         steps=[('input',
                 InputData(include=['rooms', 'surface_total', 'surface_covered',
                                    'bathrooms'],
                           include_log=['surface_total', 'surface_covered'],
                           segmentation_col='l2shp')),
                ('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('clf',
                 SGDRegressor(alpha=0.0001, average=False, early_stopping=False,
                              epsilon=1, eta0=0.01, fit_intercept=True,
                              l1_ratio=0.15, learning_rate='adaptive',
                              loss='huber', max_iter=1000, n_iter_no_change=5,
                              penalty='l2', power_t=0.25, random_state=None,
                              shuffle=True, tol=0.001, validation_fraction=0.1,
                              verbose=0, warm_start=False))],
         verbose=False)

In [86]:
results_df = pd.DataFrame(model.cv_results_)
display(results_df)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_clf,param_clf__fit_intercept,param_clf__loss,param_clf__epsilon,param_clf__learning_rate,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,5.913077,0.211911,1.822737,0.037476,"LinearRegression(copy_X=True, fit_intercept=Tr...",False,NaN,NaN,NaN,"{'clf': LinearRegression(copy_X=True, fit_inte...",-5.818203e+02,-5.723477e+02,-5.727519e+02,-5.760639e+02,-5.613079e+02,-5.728583e+02,6.697432e+00,19
1,5.821807,0.179193,1.895201,0.073499,"LinearRegression(copy_X=True, fit_intercept=Tr...",True,NaN,NaN,NaN,"{'clf': LinearRegression(copy_X=True, fit_inte...",-1.180688e-03,-6.722974e-04,-8.897820e-04,-1.307596e-03,-7.578945e-04,-9.616516e-04,2.441568e-04,2
2,5.851969,0.210612,1.718512,0.020387,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,squared_loss,NaN,NaN,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-3.497034e+14,-2.251735e+20,-1.073018e+15,-1.403052e+20,-1.228497e+20,-9.766595e+19,8.693387e+19,22
3,6.201746,0.153071,1.921244,0.101847,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,huber,0.4,invscaling,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-1.510336e-02,-7.532617e-03,-1.131848e-02,-1.501289e-02,-9.926711e-03,-1.177881e-02,2.938851e-03,8
4,7.209412,0.138920,1.838683,0.063771,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,huber,0.4,adaptive,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-4.721773e-03,-5.562442e-03,-4.931431e-03,-5.923483e-03,-6.569885e-03,-5.541803e-03,6.705316e-04,6
5,5.915323,0.138506,1.819461,0.047911,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,huber,0.7,invscaling,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-9.228338e-02,-4.755517e-03,-9.095910e-02,-7.264160e-03,-6.103363e-03,-4.027311e-02,4.193519e-02,13
6,7.141899,0.176143,1.801812,0.149674,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,huber,0.7,adaptive,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-1.190449e-03,-1.106798e-03,-1.065134e-03,-1.716721e-03,-1.548110e-03,-1.325442e-03,2.594103e-04,3
7,5.809850,0.324494,2.014303,0.165135,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,huber,1,invscaling,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-1.142095e-01,-6.380872e-03,-1.913456e-01,-3.279692e-03,-5.697472e-03,-6.418263e-02,7.634637e-02,18
8,6.908224,0.107772,1.784579,0.092168,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,huber,1,adaptive,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-1.074950e-03,-7.036605e-04,-8.508828e-04,-1.308704e-03,-8.562401e-04,-9.588873e-04,2.112742e-04,1
9,5.918402,0.179500,1.868404,0.118900,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,epsilon_insensitive,0.01,invscaling,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-1.360546e-01,-3.182252e-02,-4.197110e-02,-3.935252e-02,-2.868982e-02,-5.557811e-02,4.052701e-02,17
10,6.937736,0.123914,1.815865,0.089192,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,epsilon_insensitive,0.01,adaptive,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-1.144138e-02,-1.344350e-02,-1.217539e-02,-1.335730e-02,-1.477953e-02,-1.303942e-02,1.148269e-03,9
11,5.773601,0.237961,1.745562,0.132175,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,epsilon_insensitive,0.1,invscaling,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-6.702741e-02,-2.514314e-02,-1.282117e-01,-2.734134e-02,-2.729225e-02,-5.500316e-02,3.982150e-02,16
12,6.955959,0.234904,1.802353,0.041359,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,epsilon_insensitive,0.1,adaptive,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-1.033096e-02,-1.190736e-02,-1.070905e-02,-1.237439e-02,-1.297320e-02,-1.165899e-02,9.966622e-04,7
13,5.751304,0.115175,1.827764,0.090688,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,epsilon_insensitive,0.2,invscaling,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-1.068556e-01,-1.833322e-02,-9.055589e-02,-1.875794e-02,-1.877225e-02,-5.065498e-02,3.957073e-02,15
14,7.208236,0.095223,1.843345,0.074638,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,epsilon_insensitive,0.2,adaptive,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-3.698402e-03,-4.040365e-03,-3.459121e-03,-4.913324e-03,-5.179157e-03,-4.258074e-03,6.747891e-04,5
15,6.062134,0.143970,1.877758,0.091407,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,squared_epsilon_insensitive,0.01,invscaling,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-5.425133e+18,-9.981423e+18,-6.449595e+17,-5.982844e+19,-4.288975e+19,-2.375394e+19,2.335466e+19,21
16,13.928499,4.931143,1.827337,0.144373,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,squared_epsilon_insensitive,0.01,adaptive,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-4.399362e-02,-1.248966e-03,-3.707717e-02,-1.811812e-03,-1.357010e-03,-1.709772e-02,1.926229e-02,10
17,6.220839,0.387610,1.905085,0.081057,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,squared_epsilon_insensitive,0.1,invscaling,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-2.662256e+16,-4.568424e+19,-4.224801e+17,-8.203431e+18,-4.050412e+19,-1.896818e+19,1.998074e+19,20
18,13.635242,4.809857,1.625779,0.116670,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,squared_epsilon_insensitive,0.1,adaptive,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-6.583165e-02,-3.031063e-03,-5.294095e-02,-3.978861e-03,-2.407203e-03,-2.563795e-02,2.785980e-02,12
19,5.465670,0.147288,1.727213,0.137313,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,squared_epsilon_insensitive,0.2,invscaling,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-3.395375e+20,-2.845421e+19,-2.823919e+15,-6.491524e+19,-7.040198e+19,-1.006624e+20,1.221485e+20,23
20,13.536451,4.422428,1.726613,0.181342,"SGDRegressor(alpha=0.0001, average=False, earl...",NaN,squared_epsilon_insensitive,0.2,adaptive,"{'clf': SGDRegressor(alpha=0.0001, average=Fal...",-1.058923e-01,-9.573932e-03,-8.709013e-02,-1.089042e-02,-8.043600e-03,-4.429807e-02,4.303773e-02,14
21,59.397636,1.202645,1.900098,0.101052,"LinearSVR(C=1.0, dual=True, epsilon=0.0, fit_i...",NaN,epsilon_insensitive,NaN,NaN,"{'clf': LinearSVR(C=1.0, dual=True, epsilon=0....",-1.954666e-02,-2.288174e-02,-2.208303e-02,-2.262791e-02,-2.460474e-02,-2.234881e-02,1.635470e-03,11
22,55.658557,9.697966,1.482752,0.342960,"LinearSVR(C=1.0, dual=True, epsilon=0.0, fit_i...",NaN,squared_epsilon_insensitive,NaN,NaN,"{'clf': LinearSVR(C=1.0, dual=True, epsilon=0....",-2.234524e-03,-4.879243e-04,-4.064347e-03,-1.078574e-03,-9.053742e-04,-1.754149e-03,1.292124e-03,4

### Using the best model to predict prices in test data set

In [87]:
X_test_mod = X_test.drop(['lat','lon'], axis=1)
y_pred = best_model.predict(X_test_mod)
df_pred = pd.DataFrame({'y_pred':list(y_pred)}, index=X_test.index)
df_results = pd.concat([X_test,df_pred,y_test],axis=1)
df_results['errors'] = df_results['y_pred']-df_results['price']
df_results['l2shp'] = df['l2shp']
df_results['squared_errors'] = df_results['errors']**2
df_results['missing_lon'] = df['missing_lon']
df_results['missing_lat'] = df['missing_lat']
df_to_save = df_results[['lat','lon','l2shp','errors','squared_errors','missing_lon','missing_lat']]
display(df_to_save)
df_to_save.to_csv("test_errors.csv")

,lat,lon,l2shp,errors,squared_errors,missing_lon,missing_lat
313930,4.680539,-74.047640,CUNDINAMARCA,0.281631,0.079316,0,0
185004,3.370000,-76.518000,VALLE DEL CAUCA,0.089595,0.008027,0,0
329527,4.695075,-74.091758,CUNDINAMARCA,0.174133,0.030322,0,0
547964,NaN,NaN,SANTANDER,-0.046936,0.002203,1,1
454003,4.534566,-75.670600,QUINDIO,0.553153,0.305979,0,0
...,...,...,...,...,...,...,...
313630,NaN,NaN,CUNDINAMARCA,0.035117,0.001233,1,1
238179,4.690000,-74.060000,CUNDINAMARCA,-0.020892,0.000436,0,0
413085,10.992546,-74.821085,ATLANTICO,-0.328830,0.108129,0,0
502853,5.041843,-75.510268,CALDAS,0.555807,0.308921,0,0
84005,6.180309,-75.586620,ANTIOQUIA,-0.022645,0.000513,0,0